# Numpy 

In [0]:
x = 9

In [2]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a*b


array([ 2,  6, 12, 20])

In [6]:
who

a	 b	 np	 x	 


In [7]:
x

9

In [8]:
a = [1,2,3,4]
b= [2,3,4,5,]

ab=[]
for i in range(0, len(a)):
    ab.append(a[i]*b[i])
    
ab    

[2, 6, 12, 20]

# NumPy Arrayleri Oluşturma

In [9]:
import numpy as np
np.array([12,33,4,5])

a= np.array([12,33,4,5])

a
type(a)

numpy.ndarray

In [11]:
np.array([3.14,4,6,1.2], dtype = 'float32') # Ayrı ayrı tip bilgisi tutmak yerine hepsini tek tipe çevirdik.(verimli)

array([3.14, 4.  , 6.  , 1.2 ], dtype=float32)

In [13]:
np.zeros(10, dtype = int) # n tane 0 lardan oluşan array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
np.ones(10, dtype  = int) # n tane 1 den oluşan array

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.full((2,3),9) # 2 ye 3 lük 9lardan oluşan array

array([[9, 9, 9],
       [9, 9, 9]])

In [15]:
np.arange(0,10, 2) # bir aralık arasında k aralıklarla artan array

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(0,50,30) #  bir aralıkta n tane doğrusal(lineer) dağılımış array 

array([ 0.        ,  1.72413793,  3.44827586,  5.17241379,  6.89655172,
        8.62068966, 10.34482759, 12.06896552, 13.79310345, 15.51724138,
       17.24137931, 18.96551724, 20.68965517, 22.4137931 , 24.13793103,
       25.86206897, 27.5862069 , 29.31034483, 31.03448276, 32.75862069,
       34.48275862, 36.20689655, 37.93103448, 39.65517241, 41.37931034,
       43.10344828, 44.82758621, 46.55172414, 48.27586207, 50.        ])

In [17]:
np.random.normal(10,4 ,(3,4)) # istatistiksel özelliklerini verdim.(ort=10, std=4)

array([[10.40477815, 11.12352249, 15.39849076,  7.84712052],
       [ 4.35750798,  7.35255449, 10.48575065,  6.77089881],
       [11.64704817,  7.92972823, 11.04066365,  8.17328101]])

In [18]:
np.random.randint(0,10,(2,2)) # aralıklı rastgele int

array([[8, 5],
       [9, 6]])

In [0]:
np.eye(10) # n'e n lik 1 lerden oluşan köşegen.

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# NumPy özellikler

ndim: boyut sayısı

shape: boyut bilgisi

size. toplam eleman sayısı

dtype: array veri tipi

In [22]:
import numpy as np

a= np.random.randint(10,size = 10)
a.ndim
#a.shape
a.size 



10

In [24]:
a = np.random.randint(10,size = (2,3,5))
a

array([[[3, 9, 1, 7, 1],
        [7, 7, 4, 2, 1],
        [1, 1, 3, 5, 5]],

       [[5, 6, 5, 6, 2],
        [3, 9, 6, 4, 5],
        [4, 5, 9, 3, 3]]])

In [26]:
a.ndim # 3 boyutlu

3

In [28]:
a.shape # boyut bilgisi

(2, 3, 5)

In [30]:
a.size # eleman sayısı

30

## Yeniden şekillendirme

In [31]:
import numpy as np

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(1,10).reshape(3,3) # tek boyutlu arrayi boyutlandırdık.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a = np.array([1,2,3])
a.ndim

1

In [34]:
b= a.reshape((3,1))
b.ndim

2

In [36]:
c = np.random.randint(10, size = (5,2))
c.ndim

2

In [42]:
yeni = np.random.randint(10,size=(5,2))
yeni[np.newaxis,:] # boyut artırdık.

array([[[8, 2],
        [7, 8],
        [1, 2],
        [5, 2],
        [8, 7]]])

In [38]:
yeni = np.random.randint(10,size=(5,2))
yeni[:,np.newaxis]

array([[[6, 3]],

       [[8, 5]],

       [[9, 0]],

       [[5, 9]],

       [[7, 7]]])

In [0]:
c = np.random.randint(10, size = (5,2))
c[np.newaxis,:]

array([[[6, 4],
        [0, 5],
        [6, 3],
        [6, 5],
        [2, 8]]])

In [0]:
c = np.random.randint(10, size = (5,2))
c[:,np.newaxis]

array([[[9, 0]],

       [[7, 9]],

       [[3, 6]],

       [[1, 7]],

       [[2, 5]]])

In [0]:
a = np.array([1,2,3])

In [0]:
a.reshape([1,3])

array([[1, 2, 3]])

In [0]:
a= np.array([1,2,3])
a

array([1, 2, 3])

In [0]:
a=np.array([1,2,3])
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [0]:
a= np.array([1,2,3])
a[np.newaxis,:]

array([[1, 2, 3]])

## Concatenation

In [52]:
x = np.array([1,2,3])
y = np.array([4,5,6])

np.concatenate([x,y]) # iki array ı birleştiirir

array([1, 2, 3, 4, 5, 6])

In [0]:
z = np.array([7,8,9])

In [50]:
np.concatenate([x,y,z],axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
z[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [0]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.concatenate([b,b], axis = 1) # birleştirme eksenine axis i 1 veya 0 yaparak karar veriyoruz.

array([[1, 1],
       [2, 2],
       [3, 3]])

In [54]:
a = np.array([1,2,3])
b = np.array([4,5,6,7,8,9])
b = b.reshape(2,3)

np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


np.vstack([a,b]): vstack fonksiyonu girilen a ve b 2 çok boyutlu nesnelerini sütunsal olarak birleştrir.
np.hstack([a,b]): hstack fonksiyonu giriln a ve b  çok boyutlu metrislerini yatay olarak birleştirilir.
boyutlu metrisleri birbirleriyle birleştirme işlemlerinde hata almamak için boyutların shape lerinin uyuşması gerekir.


In [55]:
x = [1,2,3,99,3,2,1]
x

[1, 2, 3, 99, 3, 2, 1]

In [56]:
a,b,c = np.split(x, [2,4])
a

array([1, 2])

In [57]:
b

array([ 3, 99])

In [58]:
c

array([3, 2, 1])

In [0]:
m = np.arange(16).reshape([4,4])

In [0]:
a,b =np.vsplit(m,[2])

In [61]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [62]:
b

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
np.hstack([a,b])

array([[ 0,  1,  2,  3,  8,  9, 10, 11],
       [ 4,  5,  6,  7, 12, 13, 14, 15]])

In [0]:
x= np.arange(16).reshape(4,4)

In [65]:
x


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
a,b =np.hsplit(x,([2]))

In [67]:
np.vsplit(x,([2]))

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [68]:
np.hstack([a,b])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

np.vsplit(x,[n]) fonksiyonu bir x metrisini dikey olarak n parçaya böler.

np.hsplit(x,[n]) fonksiyonu bir x metrisini yatay eksende n parçaya böler.

## Array sıralama

In [0]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [0]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [0]:
v.sort() # pythona ait bir fonksiyonn ile sıralama işlemi yaptığımızda nesnede kalıcı değişik yaptı.

In [0]:
# oysaki np.sort() fonksyonunu numpy dan aldığımız için bu kalıcı değişiklik yapmadı. istediğimiz durum genellikle bu 

array([1, 2, 3, 4, 5])

In [70]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [71]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [0]:
i = np.argsort(v)

In [73]:
i

array([1, 0, 3, 2, 4])

In [74]:
v

array([2, 1, 4, 3, 5])

In [75]:
v[i]

array([1, 2, 3, 4, 5])

In [76]:
t = [ 2,3,4,5,6,43,24,1]
np.sort(t)

array([ 1,  2,  3,  4,  5,  6, 24, 43])

In [77]:
np.argsort(t)

array([7, 0, 1, 2, 3, 4, 6, 5])

In [0]:
t = [2,1,3,5,4,12,11]

In [80]:
a = np.argsort(t)
a

array([1, 0, 2, 4, 3, 6, 5])

In [82]:
t

[2, 1, 3, 5, 4, 12, 11]

In [0]:
m =([2,1,3])


In [86]:
k = np.argsort(m)
k

array([1, 0, 2])

In [0]:
n = np.array([1,3,2])

In [89]:
np.sort(n)

array([1, 2, 3])

In [0]:
i =  np.argsort(n)

In [91]:
i

array([0, 2, 1])

In [92]:
n

array([1, 3, 2])

In [0]:
n[i]

array([1, 2, 3])

In [0]:
i[n]

array([0, 2, 3], dtype=int64)

In [0]:
n[i]

array([1, 2, 3])

In [94]:
import numpy as np
a = np.random.randint(10,size= 10)
a

array([3, 1, 1, 1, 3, 4, 0, 9, 9, 9])

In [0]:
a[0]
a[-1]
a[-2]
a[9]= 10

In [96]:
a

array([ 3,  1,  1,  1,  3,  4,  0,  9,  9, 10])

In [97]:

a = np.random.randint(10, size = (3,5))
a


array([[7, 0, 7, 7, 4],
       [0, 6, 0, 0, 5],
       [8, 0, 9, 9, 2]])

In [98]:
a[1,2]

0

In [99]:
a[1,1]

6

In [0]:
a[0,0] = 10

In [101]:
a

array([[10,  0,  7,  7,  4],
       [ 0,  6,  0,  0,  5],
       [ 8,  0,  9,  9,  2]])

In [102]:
a[0,1]

0

In [0]:
a[0,1] = 44.5

In [104]:
a

array([[10, 44,  7,  7,  4],
       [ 0,  6,  0,  0,  5],
       [ 8,  0,  9,  9,  2]])

## Slicing işlemleri 

In [106]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [107]:
a[:3] # ilk 3

array([20, 21, 22])

In [108]:
a[3:] # ilk 3 ten sonrası

array([23, 24, 25, 26, 27, 28, 29])

In [0]:
a[::2]

array([20, 22, 24, 26, 28])

In [0]:
a[1::2]

array([21, 23, 25, 27, 29])

In [0]:
a[2::2]

array([22, 24, 26, 28])

In [109]:
a[3::2]

array([23, 25, 27, 29])

In [112]:
a = np.random.randint(10, size = (5,5))
a

array([[6, 7, 0, 6, 7],
       [0, 6, 2, 4, 5],
       [9, 8, 3, 7, 2],
       [5, 6, 7, 8, 3],
       [0, 7, 1, 5, 2]])

In [0]:
sifirinci_sutun = a[:,0]

In [114]:
sifirinci_sutun

array([6, 0, 9, 5, 0])

In [0]:
birinci = a[:,1]

In [116]:
birinci

array([7, 6, 8, 6, 7])

In [0]:
son = a[:,-1]

In [118]:
son

array([7, 5, 2, 3, 2])

In [0]:
sifirinci_satir = a[0,:]

In [120]:
sifirinci_satir

array([6, 7, 0, 6, 7])

In [0]:
a[0]

array([0, 8, 9, 4, 1])

In [0]:
a[:2,:3]

array([[0, 8, 9],
       [3, 7, 3]])

In [0]:
a[0:2,0:3]

array([[0, 8, 9],
       [3, 7, 3]])

In [0]:
a[::,:2]

array([[0, 8],
       [3, 7],
       [2, 2],
       [1, 8],
       [6, 2]])

In [0]:
a[:,:2]

array([[0, 8],
       [3, 7],
       [2, 2],
       [1, 8],
       [6, 2]])

In [0]:
a[1:3,0:2]

array([[3, 7],
       [2, 2]])

In [0]:
alt_a= a[0:3,0:2]

In [0]:
alt_a

array([[0, 8],
       [3, 7],
       [2, 2]])

In [0]:
alt_a[0,0] = 9999
alt_a[1,1] = 9999

In [0]:
alt_a

array([[9999,    8],
       [   3, 9999],
       [   2,    2]])

In [0]:
a

array([[9999,    8,    9,    4,    1],
       [   3, 9999,    3,    9,    1],
       [   2,    2,    8,    5,    2],
       [   1,    8,    6,    2,    9],
       [   6,    2,    8,    3,    0]])

In [0]:
a = np.random.randint(10, size = (5,5))
a

array([[6, 5, 6, 6, 5],
       [7, 9, 2, 4, 4],
       [3, 6, 1, 2, 5],
       [4, 4, 8, 2, 3],
       [7, 8, 2, 2, 7]])

In [0]:
alt = a[0:3,0:2].copy()

In [0]:
alt[0,0] = 9999
alt[1,1] = 9999

In [0]:
alt

array([[9999,    5],
       [   7, 9999],
       [   3,    6]])

In [0]:
a

array([[6, 5, 6, 6, 5],
       [7, 9, 2, 4, 4],
       [3, 6, 1, 2, 5],
       [4, 4, 8, 2, 3],
       [7, 8, 2, 2, 7]])

## Fancy index

In [0]:
v = np.arange(0,30,3)

In [0]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [0]:
v[1]
v[3]

9

In [0]:
[v[1],v[3]]

[3, 9]

In [0]:
getir = [1,3,5] # fancy index

In [0]:
v[getir]

array([ 3,  9, 15])

In [0]:
m  = np.arange(9).reshape((3,3))



satir= np.array([0,1])
sutun= np.array([1,2])
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
m[satir, sutun]

array([1, 5])

In [0]:
m[0, [1,2]]

array([1, 2])

In [0]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [0]:
v = np.arange(5,10)
v

array([5, 6, 7, 8, 9])

In [0]:
index = np.array([0,1,4])
index

array([0, 1, 4])

In [0]:
v[index] =99

In [0]:
v

array([99, 99,  7,  8, 99])

In [0]:
v[[0,1]] = [4,6]

In [0]:
v

array([ 4,  6,  7,  8, 99])

In [0]:
t = np.arange(10)
t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
index = [1,2,9]
index

[1, 2, 9]

In [0]:
t[index]= 41,42,43

In [0]:
t

array([ 0, 41, 42,  3,  4,  5,  6,  7,  8, 43])

## Koşullu Eleman İşlemleri

In [0]:
v = np.array([1,2,3,4,5])

In [0]:
v>3

array([False, False, False,  True,  True])

In [0]:
v==3

array([False, False,  True, False, False])

In [0]:
v<=3

array([ True,  True,  True, False, False])

In [0]:
v!=3

array([ True,  True, False,  True,  True])

In [0]:
(2*v)

array([ 2,  4,  6,  8, 10])

In [0]:
(v**2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [0]:
(v**2)==(2*v)

array([False,  True, False, False, False])

In [0]:
np.equal(3,v)

array([False, False,  True, False, False])

In [0]:
np.equal([0,1,3], np.arange(3))

array([ True,  True, False])

In [0]:
np.arange(3)


array([0, 1, 2])

In [0]:
v = np.random.randint(0,10,(3,3))
v

array([[0, 9, 7],
       [1, 6, 4],
       [8, 9, 7]])

In [0]:
np.equal(v[0,0], 0)

True

In [0]:
np.sum(np.equal(v[0,0], 0))  

1

sum fonksiyonu yapılan sordudaki true syısını verir.
örnek kullanım:

np.sum( n>5) veya np.sum(np.equal(v[0,0], 0)) vb.

In [0]:
np.sum((v>5) & (v<7)) #burda bir nevi v de 5 ile 7 arasında kaç değer vardır diye sorduk

1

In [0]:
np.sum(v[:,2]>0)

3

In [0]:
v[:,0]

array([0, 1, 8])

In [0]:
np.sum(v==1, axis = 0) 

array([1, 0, 0])

In [0]:
v[:,0]

array([0, 1, 8])

In [0]:
np.sum(v>0, axis = 1)

array([2, 3, 3])

In [0]:
v = np.random.randint(0,10,(3,3))
v

array([[8, 6, 6],
       [9, 2, 8],
       [8, 4, 7]])

In [0]:
np.all(v>0) # burda all() fonkksiyonun içinde o arrayin tüm elemanları üzerinde bir sorgulama yapıyoruz. 
            #Eğer tüm elemanlar o şarta uyuyorsa true  en az biri uymuyorsa false döner.

True

In [0]:
np.sum(np.all(v>0))== 1

True

In [0]:
np.any(v>4) # ny() fonksionun içinde ki sorgulam için en az bir doğru değer varsa sonuç true, 
            # hiç doğru değer yoksa false döner.

True

In [0]:
np.any(v==8, axis  =0)

array([ True, False,  True])

In [0]:
v

array([[8, 6, 6],
       [9, 2, 8],
       [8, 4, 7]])

In [0]:
v[v>3]

array([8, 6, 6, 9, 8, 8, 4, 7])

In [0]:
4* v[(v>1) & (v<3)]

In [0]:
ozel*2

array([4])

In [0]:
v

# NumPy Hesaplamalı işlemler


In [0]:
import numpy as np
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [0]:
a -1 # diziye uygulnan matemaiksel işlemleri, dizinin her elemanına uygular.

array([-1,  0,  1,  2,  3])

In [0]:
a+1

array([1, 2, 3, 4, 5])

In [0]:
a*5

array([ 0,  5, 10, 15, 20])

In [0]:
a**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [0]:
a %2

array([0, 1, 0, 1, 0], dtype=int32)

In [0]:
a

In [0]:
5*(a/2*9)

array([ 0. , 22.5, 45. , 67.5, 90. ])

In [0]:
np.add(a,2)

array([2, 3, 4, 5, 6])

In [0]:
np.subtract(a,1)

array([-1,  0,  1,  2,  3])

In [0]:
np.multiply(a,3)

array([ 0,  3,  6,  9, 12])

In [0]:
np.divide(a,2)

array([0. , 0.5, 1. , 1.5, 2. ])

In [0]:
np.power(a,2) #kuvveti

array([ 0,  1,  4,  9, 16], dtype=int32)

Çok fazla matematiksel fonksiyon var lazım olursa araştırılabilir.

In [0]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [0]:
np.add.reduce(a)

15

In [0]:
np.multiply.reduce(a)

120

In [0]:
np.add.accumulate(a) # accumulate fonksiyonu yapılan işlemin her adımını gösterir

array([ 1,  3,  6, 10, 15], dtype=int32)

In [0]:
a = np.random.normal(0,1,30)
a                                  

array([ 0.38690785,  0.04865427, -0.46710447,  0.21855572,  0.5794337 ,
        0.92408848, -0.9646908 ,  1.00303337, -0.05095134,  0.77222175,
        2.04684531, -2.61571004,  0.58402169, -0.1213574 , -0.4904107 ,
        0.09147787, -0.92269103, -1.04789028,  0.54331891,  0.35381444,
        0.64568999,  0.60664721,  0.82667518,  1.01131018, -0.35386367,
        0.16304352, -1.02980803,  0.32239112, -1.576127  ,  1.22433728])

In [0]:

np.mean(a) # mean() fonksiyonu elemnların ortlamasını alır. 

0.0903954362276422

### mean() fonksiyonu elemnların ortlamasını alır. 

In [0]:
np.std(a)

0.9254673248051901

### std() fonksiyonu elemanların standart sapmasını verir.

In [0]:
np.var(a)

0.8564897692820753

### var() fonksiyonu elemanların varyansını alır.

In [0]:
np.median(a)

0.2704734186879769

###  median() fonksiyonu elemanların medyanını alır.

In [0]:
sum(a) 

2.7118630868292666

### sum() fonksiyonu içine girilen diziyi... toplar 

In [0]:
np.min(a)
np.max(a)

2.046845305363406

### min() ve max() fonksiiyonları dizideki mnimum ve maximum değerleri bulur.

bu fonksiyonların başın nan getirirsek (nanmean() gibi)  fonksiyon eksiklere duyarlı hala gelir.

In [0]:
a = np.random.normal(0,1,(3,3))
a

array([[ 1.15645701, -1.21209183, -0.71254448],
       [-0.24647725,  0.64484699, -1.19194457],
       [ 0.41085979,  0.14719385,  1.16554721]])

In [0]:
a.sum(axis =1)

array([-0.76817931, -0.79357483,  1.72360086])

array([[ 1.15645701, -1.21209183, -0.71254448],
       [-0.24647725,  0.64484699, -1.19194457],
       [ 0.41085979,  0.14719385,  1.16554721]])

### Farklı boyutlu Array'ler ile birlikte  çalışmak


In [0]:
import numpy as np
a = np.array([1,2,3])
b = np.array([1,2,3])

a+b

array([2, 4, 6])

In [0]:
m = np.ones((3,3))
m

2

In [0]:
a+m # bu işleme bordcasting denir. yani farklı boyuttaki elamanları birbirinin üzerine yayarak birleştirmek.

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [0]:
a = np.arange(3)
a

array([0, 1, 2])

In [0]:
b = np.arange(3)[:,np.newaxis]
b

array([[0],
       [1],
       [2]])

In [0]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Pandas

### Pandas Series

In [0]:
import numpy as np
import pandas as pd

In [124]:
# numpydan temel farkı index bilgisi de internal olarak tutulur

pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [126]:
seri = pd.Series([1,3,5,7,9])
seri

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [127]:
type(seri) 

pandas.core.series.Series

In [128]:
seri.axes # indexlerin kaçtan başlayıp kaçta bittiğini veriyor 

[RangeIndex(start=0, stop=5, step=1)]

In [0]:
seri.dtype

dtype('int64')

In [0]:
seri.empty

False

In [0]:
seri.ndim

1

In [0]:
seri.size

5

In [0]:
seri.values # elemanları aarray'ler halinde verir.

array([1, 3, 5, 7, 9], dtype=int64)

In [129]:
seri.head(2) # baştan n tane elemnı verir.

0    1
1    3
dtype: int64

In [0]:
seri[0:3]

0    1
1    3
2    5
dtype: int64

In [0]:
seri.tail(2) # sondan n tane elemanı verir.

3    7
4    9
dtype: int64

In [0]:
a = np.array([1,2,3,566,88])
a

array([  1,   2,   3, 566,  88])

In [0]:
type(a)

numpy.ndarray

In [0]:
seri = pd.Series(a)  # Burda numpy arrayini pandas serisine çevirdik
seri

0      1
1      2
2      3
3    566
4     88
dtype: int32

In [0]:
seri.index # serinin index billgilerine ulaaşıyoruz.

RangeIndex(start=0, stop=5, step=1)

In [0]:
seri[0]

1

In [0]:
seri = pd.Series([1,5,0.9,34], index = [1,3,5.1,'a'])
# burda bir pandas serisi oluşturup [] içinde seri elemanlarını girip
# bunlara index atayabiliyoruz. Bu indexler int lerden oluşmak zorunda da değil
# indexler  hem str,float, int gibi birden çok türden atayabiliyoruz.

In [0]:
seri['a'] # a benim atadığım index

34.0

In [0]:
sozluk = {"reg": 10, "loj": 11, "cart": 12, "ali": "adam"}

In [0]:
sozluk

{'reg': 10, 'loj': 11, 'cart': 12, 'ali': 'adam'}

In [0]:
seri = pd.Series(sozluk) # bu işlemin sonucunda oluşturduğumuz sözlüğü bir pandas Series olarak seri adlı değişkenime atadım

In [0]:
seri["ali"] # burda index çağırma işşlemindeki gibi yaptık. ali adlı indexi çağırınca karşılığı olan value geldi.

'adam'

In [0]:
seri["reg":"ali"] # regden ali ye kadar(reg ve ali dahil.) yazdır

reg       10
loj       11
cart      12
ali     adam
dtype: object

In [0]:
pd.concat([seri,seri]) # concat() fonksiyonu ile iki tane seriyi arka arkaya birleştirebiliyoruz 

reg       10
loj       11
cart      12
ali     adam
reg       10
loj       11
cart      12
ali     adam
dtype: object

In [0]:
seri.append(seri) # seriye seri ekler

reg       10
loj       11
cart      12
ali     adam
reg       10
loj       11
cart      12
ali     adam
dtype: object

In [0]:
seri

reg       10
loj       11
cart      12
ali     adam
dtype: object

### Serilerde Eleman İşlemleri

In [130]:
a = np.array([1,2,3,33,55,66])
seri = pd.Series(a)
seri

0     1
1     2
2     3
3    33
4    55
5    66
dtype: int64

In [131]:
seri = pd.Series([121,200,150,99], index =["reg","loj","cart","rf"])
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [132]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [133]:
seri.keys # indexlere eriştim

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [134]:
list(seri.items()) #serinin hem indexlerine hem değerlerinde aynı anda bir lise içinde ulaştım.

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [135]:
seri.values


array([121, 200, 150,  99])

In [136]:
"cart" in seri # bir index isminin  seri de olup olmadığını sorguladım

True

In [137]:
seri[["rf","cart"]]

rf       99
cart    150
dtype: int64

In [0]:
seri["rf"] = 100 #rf indexinin value sini değiştiriyorum.

In [139]:
seri["rf"]

100

In [140]:
seri["reg": "rf"] # burda reg ve rf yi de dahil ediyor

reg     121
loj     200
cart    150
rf      100
dtype: int64

In [141]:
seri[0:3] #burda 0 ı alıyor 3 ü almıyor.

reg     121
loj     200
cart    150
dtype: int64

In [142]:
seri = pd.Series([121,200,150,99], index =["reg","loj","cart","rf"])
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [0]:
seri[(seri>125) & (seri<200)]

cart    150
dtype: int64

In [144]:
data = pd.Series(["a","b","c"], index=[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [145]:
data[0]
 # burada ilk indeximiz için alışılagelmişin aksine 0 yerine isimlendirdiğimiz değeri istiyor bu yüzden KeyError hatası veriyor.


KeyError: ignored

In [146]:
data[1] # burda ilk index alışılagelmiş 0 olması gerekirken isimlendirdiğimiz için ona bağlı kalmak zorundayız.

'a'

In [148]:
data[1:3] #burda isimlendirilen indexin aksine 0 ı ilk index kabulediliyor.

3    b
5    c
dtype: object

In [149]:
data[0:3] # yine burda isimlendirdiğimizin aksine 0 ı index kabul ederek işlem yapıyor. Bunlara dikkat etmek gerekir.

1    a
3    b
5    c
dtype: object

### loc: label based indexing, tanımlandığı şekkliyle index yakala.

In [150]:
data.loc[1] # kendi tanımlarımıza göre indexle çağırdık.

'a'

In [151]:
data.loc[2:5]

3    b
5    c
dtype: object

In [152]:
data

1    a
3    b
5    c
dtype: object

In [153]:
import pandas as pd
import numpy as np

data2 = pd.Series(["a","b","c","d","e"], index=[1,2,3,4,5])
data2

1    a
2    b
3    c
4    d
5    e
dtype: object

In [154]:
data2[1]

'a'

In [155]:
data2.loc[0:4] # 0 diye bir index tanımlamadım.  Burada pandas 0 ı atlladı ve 1 den devam etti.
# benim girdiğim 1.2.3.4 isimli indexleri aldı. eğer 0 dan başlasaaydı 4 ü almazdı. DİKKAT...

1    a
2    b
3    c
4    d
dtype: object

### ilock: positionel indexing, indexi 0 layarak orjinal haliyle verir. 

In [156]:
data2

1    a
2    b
3    c
4    d
5    e
dtype: object

In [157]:
data2.iloc[0]
data2.iloc[1]

'b'

# Pandas DataFrame Özellikleri & Oluşturma

In [158]:
import numpy as np
import pandas as pd



l = [1,4,577,343]         
l

[1, 4, 577, 343]

In [0]:
df = pd.DataFrame(l, columns =["değiken_ismi"] )

In [160]:
df

değiken_ismi
0             1
1             4
2           577
3           343

In [161]:
type(df)

pandas.core.frame.DataFrame

In [162]:
df.axes

[RangeIndex(start=0, stop=4, step=1), Index(['değiken_ismi'], dtype='object')]

In [163]:
df.shape

(4, 1)

In [164]:
df.ndim

2

In [165]:
df.values

array([[  1],
       [  4],
       [577],
       [343]])

In [166]:
df.size

4

In [167]:
df.head(2)

değiken_ismi
0             1
1             4

In [168]:
df.tail(2)

değiken_ismi
2           577
3           343

In [169]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [170]:
data = pd.DataFrame(a,columns = ["degisgen"] )
data

degisgen
0         1
1         2
2         3
3         4

In [171]:
data.ndim

2

In [172]:
m = np.arange(1,10).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [173]:
datam = pd.DataFrame(m, columns = ["deg","deg2", "deg3"])
datam

deg  deg2  deg3
0    1     2     3
1    4     5     6
2    7     8     9

In [0]:
datam.columns = ("deg1","deg2","deg3")

In [0]:
datam.index = ("a","b","c") # indexlerinin isimlerini degistirdir.

In [176]:
datam

deg1  deg2  deg3
a     1     2     3
b     4     5     6
c     7     8     9

In [0]:
a = pd.Series([1,2,3,4])

In [179]:
a

0    1
1    2
2    3
3    4
dtype: int64

In [0]:
df = pd.DataFrame(a)

In [181]:
df

0
0  1
1  2
2  3
3  4

In [0]:
df.index = ("a","b","c","d")

In [183]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [186]:
pd.DataFrame(pd.Series([1,2,3,4]), columns = ["deiskenler"])

deiskenler
0           1
1           2
2           3
3           4

In [0]:
m = pd.Series([1,2,3,4])
n = pd.Series([1,2,3,4])

In [189]:
pd.DataFrame({"degisken1":m,
              "degisken2":n}) # sözlük notasyonu ile dataframe isimlendirdik ve değerlerini atadık.

degisken1  degisken2
0          1          1
1          2          2
2          3          3
3          4          4

In [190]:
s1 = np.random.randint(10, size=5)
s2 = np.random.randint(10, size=5)
df = pd.DataFrame({"var1":s1,
                  "var2":s2})
df

var1  var2
0     7     9
1     3     6
2     1     2
3     2     3
4     8     1

In [0]:
df.index  = ("a","b","c","d","e")

In [192]:

df

var1  var2
a     7     9
b     3     6
c     1     2
d     2     3
e     8     1

In [193]:
df["c":"e"]

var1  var2
c     1     2
d     2     3
e     8     1

In [197]:
df.drop("a") # a indexini attı, kalıcı değil.

var1  var2
b     3     6
c     1     2
d     2     3
e     8     1

In [196]:
df

var1  var2
a     7     9
b     3     6
c     1     2
d     2     3
e     8     1

In [206]:
df.copy()

var1
a     7
b     3
c     1
d     2
e     8

In [208]:
df

var1
a     7
b     3
c     1
d     2
e     8

In [209]:
s1 = np.random.randint(10, size=5)
s2 = np.random.randint(10, size=5)
df = pd.DataFrame({"var1":s1,
                  "var2":s2})
df

var1  var2
0     2     2
1     1     5
2     8     9
3     3     4
4     1     7

In [0]:
df.index=("a","b","c","d","e")


df
l = ["a","b"]

In [0]:
df.drop(l, axis  = 0)

NameError: name 'l' is not defined

In [0]:
"var1" in df

In [0]:
l = ["var1","var2","var3"]

In [0]:
for i in l: 
    print(i in df)

NameError: name 'l' is not defined

In [0]:
df["var1"] is df["var2"]

In [0]:
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6])

df = pd.DataFrame({"var1":a,
                  "var2":b})

In [0]:
df

In [0]:
df["var1"] is df["var2"]

KeyError: 'var1'

In [0]:
df.index = ("a","b","c","d","e","f")

In [0]:
df

In [211]:
df["var2"]

a    2
b    5
c    9
d    4
e    7
Name: var2, dtype: int64

In [212]:
df.var1

a    2
b    1
c    8
d    3
e    1
Name: var1, dtype: int64

In [213]:
df.var2

a    2
b    5
c    9
d    4
e    7
Name: var2, dtype: int64

In [0]:
df["var3"] = df["var1"] + df["var2"] 

In [0]:
df

var1  var2  var3
a     1     1     2
b     2     2     4
c     3     3     6
d     4     4     8
e     5     5    10
f     6     6    12

In [0]:
df.drop(l,axis =1, inplace = True)

In [0]:
l = ["var1", "var2"]

In [0]:
df

Empty DataFrame
Columns: []
Index: [a, b, c, d, e, f]

# Gözlem ve Değişkenlere Birlikte erişmek

In [0]:
s1 = np.random.randint(10, size=5)
s2 = np.random.randint(10, size=5)
s3 = np.random.randint(10, size=5)
df = pd.DataFrame({"var1":s1,
                   "var2":s2,
                   "var3":s3})
df

var1  var2  var3
0     5     0     5
1     4     9     3
2     2     3     0
3     1     4     4
4     3     2     4

In [0]:
df.loc

[0:3]   #loc yapısıyla veriyi bizim index lerimize göre başlatıp bitirdi. Mesela 3 e kadar demek yerine 3 ü de dahil etti..

var1  var2  var3
0     6     9     4
1     8     2     2
2     3     3     3
3     2     3     7

In [0]:
df.iloc[0:3] # tamamen orjinal 0  dayalı indexlere bağlı kaldı ve 3 e kadar dedi, 3 ü dahil etmedi.

var1  var2  var3
0     6     9     4
1     8     2     2
2     3     3     3

In [0]:
df.iloc[0:3,"var1"] # Burda hata aldık çünkü iloc fonksiyonunda orjinal 0 a dayalı indexlere bğlı kalmamız gerekiyor.
                    # Kendi değişken ismimizi iloc a yazınca hhata alıyoruz.

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [0]:
df.loc[0:3, "var1":"var2"] #burda loc olduğu için kendi değişken isimerimizi kullanabiliyoruz.

var1  var2
0     6     9
1     8     2
2     3     3
3     2     3

In [0]:
df

var1  var2  var3
0     6     9     4
1     8     2     2
2     3     3     3
3     2     3     7
4     0     8     5

In [0]:
df[df.var1>5]["var1"]

0    6
1    8
Name: var1, dtype: int32

In [0]:

df.drop("var2",axis = 1, inplace = True)

In [0]:
df

var1  var3
0     6     4
1     8     2
2     3     3
3     2     7
4     0     5

In [0]:
df

var1  var3
0     6     4
1     8     2
2     3     3
3     2     7
4     0     5

In [0]:
df.loc[(df.var1>5) & (df.var3<7), ["var1","var3"]]

Empty DataFrame
Columns: [var1, var3]
Index: []

In [0]:
import numpy as np
import pandas as pd


s1 = np.random.randint(10, size=5)
s2 = np.random.randint(10, size=5)
s3 = np.random.randint(10, size=5)
df1 = pd.DataFrame({"var1":s1,
                   "var2":s2,
                   "var3":s3})


In [216]:
df2 = df1 + 99
df2

var1  var2  var3
0   108   108   102
1   108   102   106
2    99   100   102
3   108   107    99
4   106   107   104

In [217]:
pd.concat([df1,df2]) # Burda bir index problemi var. Bu ciddi bir problem.

var1  var2  var3
0     9     9     3
1     9     3     7
2     0     1     3
3     9     8     0
4     7     8     5
0   108   108   102
1   108   102   106
2    99   100   102
3   108   107    99
4   106   107   104

In [218]:
pd.concat([df1,df2],  ignore_index = True)  # ignor_index argümanıyla index problemini çözmüş olduk

var1  var2  var3
0     9     9     3
1     9     3     7
2     0     1     3
3     9     8     0
4     7     8     5
5   108   108   102
6   108   102   106
7    99   100   102
8   108   107    99
9   106   107   104

In [0]:
df2.columns = ["var1","var2","deg3"]

In [220]:
df2

var1  var2  deg3
0   108   108   102
1   108   102   106
2    99   100   102
3   108   107    99
4   106   107   104

In [221]:
df1

var1  var2  var3
0     9     9     3
1     9     3     7
2     0     1     3
3     9     8     0
4     7     8     5

In [222]:
pd.concat([df1,df2], ignore_index = True) # Burda değişken isimleri aynı olmadığı için conccat işlemi kısmi başarısız oldu.
# Eşleşmeyen değerler NaN olarak döndü.

var1  var2  var3   deg3
0     9     9   3.0    NaN
1     9     3   7.0    NaN
2     0     1   3.0    NaN
3     9     8   0.0    NaN
4     7     8   5.0    NaN
5   108   108   NaN  102.0
6   108   102   NaN  106.0
7    99   100   NaN  102.0
8   108   107   NaN   99.0
9   106   107   NaN  104.0

In [223]:
pd.concat([df1,df2], ignore_index = True, join = "inner")  # eğer NaN ler ile ilgilenmiyorsak join argümanına
#inner dediğimiz zaman eşleşmeyenler silinir ve kısımi olarak  problemi çözeriz.

var1  var2
0     9     9
1     9     3
2     0     1
3     9     8
4     7     8
5   108   108
6   108   102
7    99   100
8   108   107
9   106   107

In [226]:
pd.concat([df1,df2])

var1  var2  var3   deg3
0     9     9   3.0    NaN
1     9     3   7.0    NaN
2     0     1   3.0    NaN
3     9     8   0.0    NaN
4     7     8   5.0    NaN
0   108   108   NaN  102.0
1   108   102   NaN  106.0
2    99   100   NaN  102.0
3   108   107   NaN   99.0
4   106   107   NaN  104.0

In [0]:
df1

var1  var2  var3
0     4     5     3
1     3     0     0
2     1     5     0
3     4     5     2
4     4     0     2

In [0]:
s1 = ["Ayse","Ali","Veli","Fatma"]
s2 = ["Muhasebe","Muhendislik","Muhendislik","İK"]
df1 =pd.DataFrame({"calisanlar":s1,
                  "grup":s2})

In [0]:
a1 = ["Ayse","Ali","Veli","Fatma"]
a2 = [2010,2009,2014,2019]

df2 = pd.DataFrame({"calisanlar":a1,
                   "ilk_giris":a2})

In [0]:
df1

calisanlar         grup
0       Ayse     Muhasebe
1        Ali  Muhendislik
2       Veli  Muhendislik
3      Fatma           İK

In [0]:
df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [0]:
pd.merge(df1,df2) # burada merge fonksiyonu sayesinde ortak değikenin altında iki dataframe i birleştirdik one to one.

calisanlar         grup  ilk_giris
0       Ayse     Muhasebe       2010
1        Ali  Muhendislik       2009
2       Veli  Muhendislik       2014
3      Fatma           İK       2019

In [0]:
df3 = pd.merge(df1,df2)
df3

calisanlar         grup  ilk_giris
0       Ayse     Muhasebe       2010
1        Ali  Muhendislik       2009
2       Veli  Muhendislik       2014
3      Fatma           İK       2019

In [0]:
df4 = pd.DataFrame({"grup": ["Muhasebe","Muhendslik","İK"],
                    "mudur": ["Caner","Mustafa", "Berkcan"]})
df4

grup    mudur
0    Muhasebe    Caner
1  Muhendslik  Mustafa
2          İK  Berkcan

In [0]:
pd.merge(df3,df4) # many to one

calisanlar      grup  ilk_giris    mudur
0       Ayse  Muhasebe       2010    Caner
1      Fatma        İK       2019  Berkcan

In [0]:
df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [0]:
a1 = ["Ayse","Ali","Veli","Fatma"]
a2 = [70000,80000,120000,90000]

df2 = pd.DataFrame({"name":a1,
                   "maas":a2})

In [0]:
s1 = ["Ayse","Ali","Veli","Fatma"]
s2 = ["Muhasebe","Muhendislik","Muhendislik","İK"]
df1 =pd.DataFrame({"calisanlar":s1,
                  "grup":s2})

In [0]:
pd.merge(df1,df2, left_on = "calisanlar", right_on= "name") # bu lef ve right_on argümnlları sayesine 
# ortak olmayan değişkenleri merge hatası almadan hallediyoruz.

calisanlar         grup   name    maas
0       Ayse     Muhasebe   Ayse   70000
1        Ali  Muhendislik    Ali   80000
2       Veli  Muhendislik   Veli  120000
3      Fatma           İK  Fatma   90000

In [0]:
pd.merge(df1,df2, left_on = "calisanlar", right_on= "name").drop("name", axis = 1)
# burada drop ifadesiyle çoklanmış olan değişkenimizi axis de belirterek df den çıkarıyoruz.

calisanlar         grup    maas
0       Ayse     Muhasebe   70000
1        Ali  Muhendislik   80000
2       Veli  Muhendislik  120000
3      Fatma           İK   90000

In [0]:
df1a=df1.set_index("calisanlar") #Burada "calisanlar" ismindeki değişkenin değerlerini indx olarak atadık
df1a

grup
calisanlar             
Ayse           Muhasebe
Ali         Muhendislik
Veli        Muhendislik
Fatma                İK

In [0]:
df1a.shape 

(4, 1)

In [0]:
df1.shape

(4, 2)

In [0]:
a1 = ["Ayse","Ali","Veli","Fatma"]
a2 = [70000,80000,120000,90000]

df2 = pd.DataFrame({"calisanlar":a1,
                   "maas":a2})
df2

calisanlar    maas
0       Ayse   70000
1        Ali   80000
2       Veli  120000
3      Fatma   90000

In [0]:
df2a = df2.set_index("calisanlar")
df2a

maas
calisanlar        
Ayse         70000
Ali          80000
Veli        120000
Fatma        90000

In [0]:
df1a

grup
calisanlar             
Ayse           Muhasebe
Ali         Muhendislik
Veli        Muhendislik
Fatma                İK

In [0]:
df1a

grup
calisanlar             
Ayse           Muhasebe
Ali         Muhendislik
Veli        Muhendislik
Fatma                İK

In [0]:
df2a

maas
calisanlar        
Ayse         70000
Ali          80000
Veli        120000
Fatma        90000

In [0]:
dfa = pd.merge(df1a,df2a, left_index = True, right_index = True) # burda indexlere göre birleştirddik çünkü zaten ali vs bizim indeximiz oalarak 
#verilmiş. Eğer bize 0 1 2 diye indexler verilmiş olsaydı ve karışık calisan değerlerine sahip olsaydık bunu kullanmak mantıksız olurdu.

In [0]:
dfb = df1a.join(df2a) # yukarıdaki indexe göre birleştirme işlemini çok daha ergonomik şekilde yaptık.

In [0]:
pd.merge(dfa,dfb, on = "calisanlar") # burda görüldüğü gibi  aynı değişkenler x ve y olarak isimlendirdi.
#eğer bu aynı değişkenler isim olarak önem taşıyorsa suffixes argümanıyla bunu değiştirebiliriz.

grup_x  maas_x       grup_y  maas_y
calisanlar                                          
Ayse           Muhasebe   70000     Muhasebe   70000
Ali         Muhendislik   80000  Muhendislik   80000
Veli        Muhendislik  120000  Muhendislik  120000
Fatma                İK   90000           İK   90000

In [0]:
pd.merge(dfa,dfb, on = "calisanlar", suffixes = ["_2019", "2020"]) # BURDA DEĞİŞKENLERİ DĞİŞTTİRDİK.

grup_2019  maas_2019     grup2020  maas2020
calisanlar                                               
Ayse           Muhasebe      70000     Muhasebe     70000
Ali         Muhendislik      80000  Muhendislik     80000
Veli        Muhendislik     120000  Muhendislik    120000
Fatma                İK      90000           İK     90000

# Aggregation (toplulaştırma) işlemleri

In [229]:
import seaborn as sns # seaborn kütüphanesini import ettik

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
df = sns.load_dataset("planets") # load_data set ve isim ile birlikte bir hazır veri seti dahil ettik.

In [231]:
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [232]:
df.head

<bound method NDFrame.head of                method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]>

In [233]:
df.shape

(1035, 6)

In [234]:
df.count

<bound method DataFrame.count of                method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]>

In [235]:
df["mass"].count()

513

In [236]:
df.describe() # istatistiksel bilgilere ulaştık.

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [237]:
df["mass"].describe()

count    513.000000
mean       2.638161
std        3.818617
min        0.003600
25%        0.229000
50%        1.260000
75%        3.040000
max       25.000000
Name: mass, dtype: float64

In [238]:
df.mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [239]:
df.dropna().count() # na yleri gösterdik ve count ile saydırdık.

method            498
number            498
orbital_period    498
mass              498
distance          498
year              498
dtype: int64

In [240]:
df.dropna().describe() # na lerin istatistiklerine ulaştık.

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

# Gruplama işlemleri

In [0]:
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                  "veri": [10,11,52,23,43,55]})
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [0]:
df.groupby("gruplar") # groupby fonksiyonu sayesinde verinin gruplar adlı kategorik değişkeni gruplandırıldı ancak şu an arka planda.

In [0]:
df.groupby("gruplar").sum() # önce gruplama işlemi tamamlandı ondan sonra ne yapmasını gerektiğini söyledik.
# örneğin burda sum fonksiyonu ile gruplandırılan ellemanları topladı.
# A larla  A lar, B lerle B ler, C lerle C ler gruplandırıldı.

veri
gruplar      
A          33
B          54
C         107

In [0]:
import seaborn as sns
import pandas as pd

In [0]:
df = sns.load_dataset("planets")


In [0]:
df.head() # head kullanmak ilk iş olmalı düzenliyor.

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [0]:
df.groupby("method")

In [0]:
df.groupby("method")["orbital_period"].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [0]:
df.groupby("number").median()

orbital_period    mass  distance  year
number                                        
1             66.26200  1.7900    77.820  2009
2             42.63180  0.9900    46.340  2011
3             33.94100  0.0580    30.075  2011
4             43.37030  0.6876    13.470  2008
5             13.91331  0.4860   296.500  2011
6             36.82300  0.0194    26.110  2010
7             91.93913     NaN   780.000  2013

In [0]:
df.groupby("method")["orbital_period"].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

In [249]:
import numpy as np
import pandas as pd
import seaborn as sns


df = pd.DataFrame({"gruplar": ["A","B","C","A","B","C"],
                  "degisken1": [10,23,33,22,1,99],
                  "degisken2":[100,253,333,262,111,969]})
df

df = df.groupby("gruplar").sum()           
df

degisken1  degisken2
gruplar                      
A               32        362
B               24        364
C              132       1302

### Aggregate,Filter ,Apply,Transform fonksiyonları

In [250]:
df.groupby("gruplar").aggregate([min, np.median,max]) # Burada 'gruplar' üzerinden grupladığımız dataframe i belli istatistiksel veriler 
#üzerine gruplandırmak için aggregate([]) diyoruz vee istediğimiz istatistiksel fonksiyyonları kullanabiliyoruz.
#mesela  burada min max ve medyan değerlerini istedik.

degisken1             degisken2             
              min median  max       min median   max
gruplar                                             
A              32     32   32       362    362   362
B              24     24   24       364    364   364
C             132    132  132      1302   1302  1302

In [251]:
df.groupby("gruplar").aggregate({"degisken1":min, # kategorik değişkenleri gruplar adı altına topladık. 
                                "degisken2":max})   #aggregate fonksiyonu içinde ddeğişkenlerimizi sözlük olarak oluşturduk. 
                                                   # sözlük lerin value lerine de değerlerimin istatistiksel(min max örneği)
                                                   #değerlerini atadım.

degisken1  degisken2
gruplar                      
A               32        362
B               24        364
C              132       1302

In [0]:
def filter_func(x):
    return x["degisken2"].std()>4  
# değişken2 nin standart sapması 4 ten büyük olanlarını aldım.
# filitreleme işleminde kullanmak amacıyla kendi amacım doğrultusunda fonksiyon yazdım.

In [253]:
df.groupby("gruplar").filter(filter_func) # kendi yazdığım fonksiyonu filter içind kullanarak amacımı gerçekleştirdim.
# Bu bir indirgeme fonksiyonudur. Karmaşık verinin içinden kendi istediğimiz şartlara uyan veri seetini çekeriz.

Empty DataFrame
Columns: [degisken1, degisken2]
Index: []

In [254]:
df.groupby("gruplar").transform(lambda x: x-x.mean())  # Burda  gruplar altında groupby ettik.
#sonra transform fonksiyonun içinde yapmayı istediğimiz işe yönelik isimsiz fonksiyon yazdık.

degisken1  degisken2
gruplar                      
A              0.0        0.0
B              0.0        0.0
C              0.0        0.0

In [255]:
df.groupby("gruplar").transform(lambda x: (x-x.mean()) / x.std())

degisken1  degisken2
gruplar                      
A              NaN        NaN
B              NaN        NaN
C              NaN        NaN

In [0]:

df.groupby("gruplar").apply(np.sum)
df.groupby("gruplar").apply(np.mean)
#böylece kategorik değişkenlerin üzerine istatistiksel işlemler yaapabiliyoruz.

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             12.0      182.0
C             66.0      651.0

In [0]:
df.groupby("gruplar").sum()

degisken1  degisken2
gruplar                      
A               32        362
B               24        364
C              132       1302

In [0]:
df.groupby("gruplar").apply(np.sum)

gruplar  degisken1  degisken2
gruplar                              
A            AA         32        362
B            BB         24        364
C            CC        132       1302

In [0]:
df.groupby(["gruplar"]).sum()

degisken1  degisken2
gruplar                      
A               32        362
B               24        364
C              132       1302

In [0]:
L = [0,1,0,1,2,0]

In [0]:
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B          1        111
5       C         99        969

In [0]:
df.groupby(L).sum() # burada normalde df in kendine ait 6 tane indexi vardı. Ve ben sum dediğimde onlaarı kategorik olarak topluyordu.
# ama ben groupby kısmına L diye farklı bir değişken üzerinden gruplandırdığımda artık yeni indexler bu yeni listem oluyor.
# ve sum deyince de bu benim listemin index değerlerine göre ktegorilendirip topladı.

degisken1  degisken2
0        142       1402
1         45        515
2          1        111

In [0]:
import seaborn as sns
import pandas as pd
df= sns.load_dataset("titanic")
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [0]:
df.groupby("sex")["survived"].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [0]:
df.groupby(["sex", "class"])["survived"].aggregate("mean").unstack()

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [0]:
df.groupby(["sex", "class"])["survived"].mean().unstack()

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [0]:
df.pivot_table("survived", index = "sex", columns = "class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [0]:
age = pd.cut(df["age"], [0,18,90])
age

0      (18.0, 90.0]
1      (18.0, 90.0]
2      (18.0, 90.0]
3      (18.0, 90.0]
4      (18.0, 90.0]
           ...     
886    (18.0, 90.0]
887    (18.0, 90.0]
888             NaN
889    (18.0, 90.0]
890    (18.0, 90.0]
Name: age, Length: 891, dtype: category
Categories (2, interval[int64]): [(0, 18] < (18, 90]]

In [0]:
df.pivot_table("survived", index = "sex", columns = "embark_town")

embark_town  Cherbourg  Queenstown  Southampton
sex                                            
female        0.876712    0.750000     0.689655
male          0.305263    0.073171     0.174603

In [0]:
df.pivot_table("survived",["sex",age], "class")

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

In [0]:
fare =  pd.qcut(df["fare"],2)


df.pivot_table("survived",["sex",age],[fare,"class"])

fare            (-0.001, 14.454]                     (14.454, 512.329]  \
class                      First    Second     Third             First   
sex    age                                                               
female (0, 18]               NaN  1.000000  0.714286          0.909091   
       (18, 90]              NaN  0.880000  0.444444          0.972973   
male   (0, 18]               NaN  0.000000  0.260870          0.800000   
       (18, 90]              0.0  0.098039  0.125000          0.391304   

fare                                 
class              Second     Third  
sex    age                           
female (0, 18]   1.000000  0.318182  
       (18, 90]  0.914286  0.391304  
male   (0, 18]   0.818182  0.178571  
       (18, 90]  0.030303  0.192308

In [0]:
df.pivot_table(index = "sex", columns = "class",
              aggfunc = {"survived": sum, "fare":"mean"})

fare                       survived             
class        First     Second      Third    First Second Third
sex                                                           
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47

In [0]:
df.pivot_table("survived", index = "sex", columns = "class", margins= True)

# pivot_table ın en başına asıl karşılaştırdığımız içteki değişkeni giriyoruz(mesela survived)
# index = diyerek saatırlardaki male femle tarzı oluşturacak ,index yerine kullanılanlar, değişkenimi belirtiyorm(mesela sex)
#sütunda yani indexlerin valuesi için bakılan değişkennleri (mesela fırst second...) atamak için ccolumns diyoruz.
#margins diyerek eğerlere bir all adında değişken ekleyerek toplatıyoruz.


class      First    Second     Third       All
sex                                           
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838

In [0]:
df.pivot_table("survived", index = ["sex","who"], columns = "class", margins= True)
# burada cinsiyetin olduğu index kısmına köşelli parantez içine alarak bir değişken daha ekledik 

class            First    Second     Third       All
sex    who                                          
female child  0.666667  1.000000  0.533333  0.651163
       woman  0.978022  0.909091  0.491228  0.756458
male   child  1.000000  1.000000  0.321429  0.525000
       man    0.352941  0.080808  0.119122  0.163873
All           0.629630  0.472826  0.242363  0.383838

In [0]:
df.pivot_table("survived", index = "sex", columns = ["class","who"], margins= True)
#Class a köşeli parantezle bir değişken daha atadık. columns ile

class      First                     Second                         Third  \
who        child       man     woman  child       man     woman     child   
sex                                                                         
female  0.666667       NaN  0.978022    1.0       NaN  0.909091  0.533333   
male    1.000000  0.352941       NaN    1.0  0.080808       NaN  0.321429   
All     0.833333  0.352941  0.978022    1.0  0.080808  0.909091  0.431034   

class                            All  
who          man     woman            
sex                                   
female       NaN  0.491228  0.742038  
male    0.119122       NaN  0.188908  
All     0.119122  0.491228  0.383838

In [0]:
df.pivot_table("survived",  "sex",  ["class","who"], margins= True)
# Yukarıda yaptığımız işlemin aynısını index ve columns vermeden de yapabilirdik.
#unutma 1. içteki ana unsur 2.  satırlar(index), 3. sütun değişkenleri

class      First                     Second                         Third  \
who        child       man     woman  child       man     woman     child   
sex                                                                         
female  0.666667       NaN  0.978022    1.0       NaN  0.909091  0.533333   
male    1.000000  0.352941       NaN    1.0  0.080808       NaN  0.321429   
All     0.833333  0.352941  0.978022    1.0  0.080808  0.909091  0.431034   

class                            All  
who          man     woman            
sex                                   
female       NaN  0.491228  0.742038  
male    0.119122       NaN  0.188908  
All     0.119122  0.491228  0.383838

In [0]:
df1a = df.pivot_table("survived",  "sex",  ["class","who"], margins= True)
df1a.shape


(3, 10)

In [0]:
fare =  pd.qcut(df["fare"],2)


df.pivot_table("survived",["sex",age],[fare,"class"])
fare.head()

0     (-0.001, 14.454]
1    (14.454, 512.329]
2     (-0.001, 14.454]
3    (14.454, 512.329]
4     (-0.001, 14.454]
Name: fare, dtype: category
Categories (2, interval[float64]): [(-0.001, 14.454] < (14.454, 512.329]]

In [0]:
age = pd.qcut(df["age"],2)
age

0      (0.419, 28.0]
1       (28.0, 80.0]
2      (0.419, 28.0]
3       (28.0, 80.0]
4       (28.0, 80.0]
           ...      
886    (0.419, 28.0]
887    (0.419, 28.0]
888              NaN
889    (0.419, 28.0]
890     (28.0, 80.0]
Name: age, Length: 891, dtype: category
Categories (2, interval[float64]): [(0.419, 28.0] < (28.0, 80.0]]

In [0]:
age = pd.cut(df["age"],2)
age = pd.DataFrame(age)

In [0]:
age

age
0    (0.34, 40.21]
1    (0.34, 40.21]
2    (0.34, 40.21]
3    (0.34, 40.21]
4    (0.34, 40.21]
..             ...
886  (0.34, 40.21]
887  (0.34, 40.21]
888            NaN
889  (0.34, 40.21]
890  (0.34, 40.21]

[891 rows x 1 columns]

In [0]:
!pip install dfply
# burda r için dfply adlı kütüphane dahil ettik
# burda dahil etme yöntemini gösterdim önemli değil yoksa

In [0]:
pwd # çalışma dizinini görüüyoruz.

'C:\\Users\\semre\\Veri_manipulasyonu'

In [0]:
import pandas as pd


In [0]:
pd.read_csv("ornekcsv.csv", sep = ";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [0]:
pd.read_csv("duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [0]:
dfb = pd.read_csv("duz_metin.txt") # text doyamı seçip not olarak kullanıp değerlerini değiştirip kaydedip 
#burada değişmiş bir şekilde kullanbiliriz.

In [0]:
pd.read_excel("ornekx.xlsx")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [0]:
df = pd.read_excel("ornekx.xlsx")
df

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [0]:
df.dropna().count()

a    12
b    12
c    12
dtype: int64